apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx-deployment
  name: nginx-service
  namespace: for-argo
spec:
  ports:
  - port: 80
    nodePort: 30036
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx-deployment
  type: NodePort
